name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs: 
    build:
     runs-on: ubuntu-latest
     
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: myacrdevops.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build and Push 
        run: |
          docker build -t myacrdevops.azurecr.io/nginx-demo .
          docker push myacrdevops123.azurecr.io/nginx-demo
    
  
